server:
  port: 8081


# database connectivity
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/Microservices-UserService
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  application:
    name: USER-SERVICE

# eureka server setting
eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8080/eureka


# actuator setting
management:
  health:
    circuit-breakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always


# resilience4j setting
resilience4j:
  circuitbreaker:
    instances:
      ratingHotelBreaker:
        register-health-indicator: true
        event-consumer-buffer-size: 10
        failure-rate-threshold: 50
        minimum-number-of-calls: 5
        automatic-transition-from-open-to-half-open-enabled: true
        wait-duration-in-open-state: 6s
        permitted-number-of-calls-in-half-open-state: 3
        sliding-window-size: 10
        sliding-window-type: count_based
    circuit-breaker-aspect-order: 1     # then circuit breaker work if retry not work

  # Retry setting
  retry:
    instances:
      ratingHotelBreaker:
        max-attempts: 5
        wait-duration: 10ms
    retry-aspect-order: 2     # firstly retry will be performed

  # RateLimiter setting
  ratelimiter:
    instances:
      userRateLimiter:
        limit-refresh-period: 4s
        limit-for-period: 2
        timeout-duration: 0s