server:
  port: 8083


spring:
  datasource:
    url: jdbc:mysql://localhost:3306/Microservices-RatingService
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  application:
      name : RATING-SERVICE

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8080/eureka
